[package]
name = "crst"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
lazy_static = "1.5.0"
native-dialog = "0.7.0"
winapi = { version = "0.3.9", features = ["winbase", "ioapiset", "winnt", "handleapi", "winioctl", "winuser"] }
